# - hosts: all
#   become: true
#   roles:
#     # - install_nginx
#     - install_docker

- hosts: manager
  become: true
  roles:
    - docker_swarm_manager

- hosts: worker
  become: true
  roles:
    - docker_swarm_worker

- hosts: manager
  become: true
  roles:
    - deploy_stack