version: '3'
services:
  app:
    image: "clsyan/node-webapp:firsttry"
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure