---
- name: Copy docker-compose to remote host
  copy:
    src: "docker-compose.yml"
    dest: "/opt/docker-compose.yml"

- name: Deploy stack
  docker_stack:
    state: present
    name: app
    compose:
      - "/opt/docker-compose.yml"