---
- name: Init Docker Swarm
  community.docker.docker_swarm:
    state: present
  register: init_swarm

- name: Get join token
  set_fact:
    join_token_worker: "{{ init_swarm.swarm_facts.JoinTokens.Worker }}"